services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_data
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongodb_data:/data/db 
    networks:
      - my-game-network

  data_service:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: my-game-data
    container_name: my-game-data-container
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mongodb
    networks:
      - my-game-network

networks:
  my-game-network:
    driver: bridge